const products = () => {
    return ([
        {
          _id: "1",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "2",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "3",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "4",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "5",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "6",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "7",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "8",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "9",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "10",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "11",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "12",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "13",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "13",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "13",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "13",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "13",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "13",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "13",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "13",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "13",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "13",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "13",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "13",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "13",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "13",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        {
          _id: "13",
          name: "تخته فرش 12متری",
          image: "../public/images/gYW-FdMd.webp",
          quality:'کارکرده',
          price: "۲,۲۰۰,۰۰۰ تومان",
          address: "لحظاتی پیش در خمینی‌شهر",
        },
        
      ]);
}
 
export default products;